#!/usr/bin/env bash
# Writes /etc/nginx/snippets/cloudflare-realip.conf from Cloudflare's published IP ranges, so
# nginx logs (and $remote_addr) show real client IPs. Run as root; re-run occasionally.
set -euo pipefail
out=/etc/nginx/snippets/cloudflare-realip.conf
tmp=$(mktemp)
{
  echo "# Generated by update-cloudflare-ips.sh on $(date -u +%F)"
  for ip in $(curl -fsS https://www.cloudflare.com/ips-v4) $(curl -fsS https://www.cloudflare.com/ips-v6); do
    echo "set_real_ip_from $ip;"
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$tmp"
install -D -m 644 "$tmp" "$out"
rm -f "$tmp"
nginx -t && systemctl reload nginx
echo "Updated $out"
